### ISSUE TITLE
tomato pie is disabled

### ISSUE THREAD

**Issue by max3a3** [t9tio/blog#17]
I tried installing from .crx, it is also not working.

Please get it working again, if not let me know how can I get my data out from chrome local storage. I have my some notes I'd like to recover

**Comment by max3a3** [comment]
![image](https://user-images.githubusercontent.com/37000137/180092121-932946e7-5645-4a34-8b8e-2a28325d98dc.png)

**Comment by timqian** [comment]
@max3a3 Thanks for the report. I will update the extension and try to republish it when I got time. Before I do that. You can try enabling this extension first (Click the toggle on the right bottom)
<img width="416" alt="Screen Shot 2022-07-21 at 09 48 41" src="https://user-images.githubusercontent.com/5512552/180112176-344c4766-b975-4e8c-bed5-7c2dc9805b97.png">

**Comment by max3a3** [comment]
yeah, that work, i guess the error message shocked me so much that I miss the toggle
